In [2]:
import numpy as np

In [3]:
y = np.array([1,2,3,4,5])
y

array([1, 2, 3, 4, 5])

In [4]:
np.maximum(y, 2)**2

array([ 4,  4,  9, 16, 25], dtype=int32)

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 0, 2, 5])
c = np.linalg.norm((a - b))
d = np.linalg.norm((a - b), ord=1)

In [11]:
a-b

array([-1,  2,  1, -1])

In [12]:
c

2.6457513110645907

In [13]:
d

5.0

In [14]:
c**2

7.000000000000001

In [15]:
(a-b)*(a-b)

array([1, 4, 1, 1])

In [16]:
m = np.arange(8).reshape(4,2)

In [17]:
m

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [20]:
np.linalg.norm(m, ord=1, axis = 1)

array([ 1.,  5.,  9., 13.])

In [23]:
np.array([1+j*2 for j in [1,2,3]])

array([3, 5, 7])

In [22]:
np.array(j*2 for j in [1,2,3])

array(<generator object <genexpr> at 0x0000000004F2E150>, dtype=object)

In [25]:
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
s = np.random.rand(20,3)
s

array([[0.75366364, 0.01091272, 0.10089643],
       [0.92342685, 0.33406181, 0.13360207],
       [0.995166  , 0.0996784 , 0.0878502 ],
       [0.78356142, 0.64942629, 0.43864495],
       [0.7075806 , 0.65952431, 0.48804047],
       [0.62068587, 0.74019357, 0.67880755],
       [0.42284983, 0.23121463, 0.36319133],
       [0.86837565, 0.38087378, 0.4787274 ],
       [0.13823715, 0.43040263, 0.48566662],
       [0.6205766 , 0.34614711, 0.93806618],
       [0.02626008, 0.64999826, 0.05852196],
       [0.15764708, 0.57342002, 0.95470214],
       [0.9840355 , 0.01222977, 0.48130853],
       [0.17387757, 0.44581331, 0.03935115],
       [0.46839113, 0.28172846, 0.58565963],
       [0.26876925, 0.79438666, 0.70535613],
       [0.1659277 , 0.85263034, 0.49993277],
       [0.40809238, 0.56447981, 0.6878929 ],
       [0.02656345, 0.55738677, 0.00998055],
       [0.25162347, 0.24244416, 0.52161647]])

In [31]:
a = s[np.array([1+j*10 for j in [0, 1]])]

In [32]:
a

array([[0.92342685, 0.33406181, 0.13360207],
       [0.15764708, 0.57342002, 0.95470214]])