In [1]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [5]:
import numpy as np
a = np.array([2,4,6,8,10,12,14,16])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [7]:
np.sum(a[[1,2,3]])

18

In [10]:
b = np.where(a>4)[0]
b

array([2, 3, 4, 5, 6, 7], dtype=int64)

In [11]:
a[b]

array([ 6,  8, 10, 12, 14, 16])

In [12]:
a[np.array([2,3])]

array([6, 8])

In [40]:
h = np.arange(15)
k = np.arange(10)
print(h)
print(k)
M = [2,3,4,5,6,7]
N = [1,2,3,4,5]
s = 0
for i in N:
    for j in M:
        s += h[i] + h[j]*k[j]
q = np.sum(h[N]+h[M]*k[M])
q-s

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4 5 6 7 8 9]


ValueError: operands could not be broadcast together with shapes (5,) (6,) 

20

20

In [13]:
from random import choice
choice([i for i in range(0,9) if i not in [2]])

6

In [25]:
import numpy as np
np.random.randint(0,2)

0

Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [4]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.76339321 0.45358764]
 [0.64985691 0.23205002]]


Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [5]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [6]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [7]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [8]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [9]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a*b)
print(b*a)
print(a*(b.T))

[ 4 10 18]
[ 4 10 18]
[ 4 10 18]


In [11]:
a = np.array([[1], [2], [3]])
b = np.array([[5], [6], [7]])
print(a*b)
print(a*b.T)

[[ 5]
 [12]
 [21]]
[[ 5  6  7]
 [10 12 14]
 [15 18 21]]


In [12]:
a = np.array([1,2,3])
b = np.array([[5], [6], [7]])
print(a*b)
print(b*a)
print(a*b.T)
print(b.T*a)

[[ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]]
[[ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]]
[[ 5 12 21]]
[[ 5 12 21]]


In [13]:
(a*b.T).shape[:]

(1, 3)

In [14]:
a = np.array([[1,2,3]])
b = np.array([[4], [5], [6]])
print(a*b)
print(b*a)
print(a*b.T)
print(b.T*a)

[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[[ 4 10 18]]
[[ 4 10 18]]


In [15]:
a.T

array([[1],
       [2],
       [3]])

//* is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices

In [16]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.array([[-2], [-3]])
t = np.array([[-2, -3]])

u = np.array([-2,-3])
v = np.array([11,12])

In [17]:
print(np.dot(x,y)) # Matrix / matrix product; both produce the rank 2 array
print(np.dot(y,x))

print(np.dot(u,v)) # Inner product of vectors; both produce -58
print(np.dot(v,u))

print(np.dot(x,z)) 
print(np.dot(x,t))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
-58
-58
[[ -8]
 [-18]]


ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [ ]:
print(np.dot(x,u)) # Matrix / vector product; both produce the rank 1 array
print(np.dot(u,x))

Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:



In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

### CS231n 

In [ ]:
np.squeeze(x)

In [ ]:
x.squeeze()

In [ ]:
x = np.array([[[0], [1], [2]]])

In [ ]:
x

In [ ]:
np.squeeze(x)

In [ ]:
y=np.array([[[1],[3]], [[5],[7]], [[9],[11]]])

In [ ]:
y

In [ ]:
y.shape[:]

In [ ]:
y.squeeze()

In [ ]:
y.squeeze().shape[:]

In [ ]:
h = np.arange(12).reshape((3,4))


In [ ]:
h

In [ ]:
h.sum(axis=0)

In [ ]:
W=np.arange(12).reshape((4,3))
W

In [ ]:
X=np.arange(24).reshape((6,4))
X

In [ ]:
f = X.dot(W)
f

In [ ]:
f -= np.max(f, axis=1, keepdims=True) # max of every sample
print(f)

In [ ]:
sum_f = np.sum(np.exp(f), axis=1, keepdims=True) #tinh tong theo tung hang
p = np.exp(f)/sum_f
print(sum_f)
print(p)

In [ ]:
p[np.arange(6), [0,2,1,2,1,2]]

In [ ]:
y=[0,2,1,2,1,2]
m=np.choose(y, f.T).T.reshape(6,1) 
print m

In [ ]:
margins=np.maximum(0, f - m + 1)
margins

In [ ]:
margins[np.arange(margins.shape[0]), y]=0

In [ ]:
margins

In [ ]:
F = (margins > 0).astype(int)
F

In [ ]:
F[np.arange(F.shape[0]),y] = np.sum(-F, axis = 1)
F

In [ ]:
a = np.array((1,2,3))
b = np.array((5,6,7))
a

In [ ]:
a.T

In [ ]:
classes = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
print classes
print enumerate(classes)

In [ ]:
h=np.array((1,2,3,4,5,6,7))
g=h.reshape(-1,1)
print g
print g.shape[:]

In [ ]:
s = np.arange(15).reshape(5,3)
s

In [ ]:
a = np.array([1,2,3]).reshape(3,1)
s.dot(a)

In [ ]:
s = (3,4)
s

In [ ]:
type(s)

In [ ]:
s[0]

In [ ]:
s[1]

In [ ]:
s = np.array([1.2, -0.9, 1.5, 4, -1.8, -2.7])
s

In [ ]:
np.where(s>0,1,0)

In [ ]:
from scipy.sparse import csr_matrix, lil_matrix

In [ ]:
s = lil_matrix((3,4))

In [ ]:
s

In [ ]:
s.shape[0]

In [19]:
s = np.array([1,2,3])
s[np.newaxis,:]

array([[1, 2, 3]])