In [1]:
import numpy as np
s = np.ones((5,1))

In [2]:
h = np.random.rand(10)
h

array([ 0.07727664,  0.51124215,  0.80603991,  0.91212598,  0.6278294 ,
        0.26859702,  0.33357671,  0.95790813,  0.03979553,  0.89922203])

In [3]:
h.shape[0]

10

In [2]:
s

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [3]:
a = np.random.rand(5,3)
a

array([[0.65784657, 0.59864992, 0.5187946 ],
       [0.58170525, 0.28573104, 0.76558785],
       [0.95226653, 0.81405318, 0.81209753],
       [0.44552473, 0.2605824 , 0.02722712],
       [0.44467689, 0.29313422, 0.25996494]])

In [4]:
a[:, 1]

array([0.59864992, 0.28573104, 0.81405318, 0.2605824 , 0.29313422])

In [6]:
a[:,1]=s

ValueError: could not broadcast input array from shape (5,1) into shape (5)